

name: daily task
on:
  push:
    branches:
      - main
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name : Running script file
        run: python index.py
        
      - name: Commit report
        run: |
          git config --global user.name 'Naveenkumar M'
          git config --global user.email 'naveen9715568487@gmail.com'
          git add .
          git commit -am "Daily quotes"
          git push origin main
